### ISSUE TITLE
Where are these two files "sa_results.txt" and "tox_results.txt"

### ISSUE THREAD

**Issue by xuzhang5788** [pulimeng/eToxPred#3]
I am retraining your models. I want to compare my retrained models with yours. You said "The results of our experiments in terms of SAscores and Tox-scores are also provied in sa_results.txt and tox_results.txt". But I couldn't find them?

**Comment by pulimeng** [comment]
Hmm. That could be a mistake. I'll have to verify that with my PI on Monday. And I will upload that at that time. Sorry about that

**Comment by pulimeng** [comment]
I checked the files. They are actually under the wrong file name. It is suppose to be `train_SA_data.smi` and `train_Tox_data.smi`.

**Comment by xuzhang5788** [comment]
train_SA_data.smi and train_Tox_data.smi are training data at
https://osf.io/m4ah5/. I couldn't find them in your github of eToxPred.
Many thanks

**Comment by pulimeng** [comment]
I've uploaded the files to this repo.

**Comment by xuzhang5788** [comment]
@pulimeng 
Thank you for your uploading. If your test file is tcm600_nr.smi, id should start with tcm***. However, your ids are starting with DB***.

**Comment by pulimeng** [comment]
I can upload tcm results. However, it is just a qualitative evaluation of the approach since the TCM dataset has no label. I posted SA and toxicity results since it is comparable. The dataset used for SA and toxicity is posted in the corresponding site in readme.

**Comment by xuzhang5788** [comment]
Thank you very much.
For SA scores, the range of your training is from 1 to 10. But I got tcm's scores are min=15.18, max=75.39. This range is way out of the range of training data. So, I doubt either my training has problems, or the model has bad the generalization ability.

**Comment by pulimeng** [comment]
I don't think bad generalization can create such big difference. It sounds like your results is 10 * what it should be. I normalized the score to 0 - 1 in my script and times the results by 10 when producing. Probably you didn't normalize the original input that leads to 10 * the output.

**Comment by xuzhang5788** [comment]
@pulimeng 
I think your SA score problem is a regression problem. So, we don't need to normalize the target values.

**Comment by pulimeng** [comment]
It has nothing to do with regression or classification. I did it for the numerical stability. It is not a must.

**Comment by xuzhang5788** [comment]
@pulimeng 
Thank you. Please mention it at your readme. Because the training data you provided didn't scale to (0,1) and your load data function didn't scale it as well.

**Comment by pulimeng** [comment]
Will do. I'll just change the code itself.
