### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by stoufa** [pulimeng/eToxPred#4]
I'm facing some issues with installing this software, more precisely clashes in the versions of the different libraries used (despite using `conda`, a well-known package management system).

Can we please get more details on the development environment in which the software was created?
Ideally, a `requirements.txt` or `Dockerfile` file.

Thanks.

**Comment by pulimeng** [comment]
I've recently updated all the codes to keep up with the latest versions of some of the dependencies. And everything can be installed via Anaconda. The README file is also updated. Can you redownload everything and let me know if they are working properly. Thanks

**Comment by stoufa** [comment]
Yes! Everything works fine now, thanks a lot.
I like how you changed the code to save the final result in one CSV file (previously saved in two separate files).
Great job.
